/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#0051df",
        "primary-container": "#2f6bff",
        "surface-tint": "#0051e0",
        "inverse-primary": "#b5c4ff",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b5c4ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#000318",
        "on-primary-fixed": "#00174d",
        "on-primary-fixed-variant": "#003cac",
        secondary: "#525e7f",
        "on-secondary": "#ffffff",
        "secondary-container": "#cad6fe",
        "on-secondary-container": "#515d7e",
        "secondary-fixed": "#dae2ff",
        "secondary-fixed-dim": "#bac6ec",
        "on-secondary-fixed": "#0d1a38",
        "on-secondary-fixed-variant": "#3a4666",
        tertiary: "#a33e00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#cb4f00",
        "on-tertiary-container": "#ffffff",
        "tertiary-fixed": "#ffdbcd",
        "tertiary-fixed-dim": "#ffb596",
        "on-tertiary-fixed": "#360f00",
        "on-tertiary-fixed-variant": "#7c2d00",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        surface: "#f8f9fc",
        "on-surface": "#191c1e",
        "on-surface-variant": "#434655",
        "surface-dim": "#d9dadd",
        "surface-bright": "#f8f9fc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3f6",
        "surface-container": "#edeef1",
        "surface-container-high": "#e7e8eb",
        "surface-container-highest": "#e1e2e5",
        "surface-variant": "#e1e2e5",
        background: "#f8f9fc",
        "on-background": "#191c1e",
        outline: "#737687",
        "outline-variant": "#c3c5d8",
        "inverse-surface": "#2e3133",
        "inverse-on-surface": "#f0f1f4",
        "sidebar-bg": "#0F1C3A",
        "sidebar-text": "#8FA0BE",
        "status-active": "#16A34A",
        "status-active-bg": "#DCFCE7",
        "status-suspended": "#EAB308",
        "status-suspended-bg": "#FEF6D6",
        "status-churned": "#DC2626",
        "status-churned-bg": "#FDE3E3",
        "status-trial": "#2F6BFF",
        "status-trial-bg": "#E2EBFF",
        "plan-starter": "#F2ECFB",
        "plan-growth": "#E8F4F9",
        "plan-pro": "#ECEEF8",
        "plan-enterprise": "#0F1C3A",
      },
      spacing: {
        "page-padding-x": "32px",
        "container-max": "1440px",
        "sidebar-collapsed": "76px",
        "header-height": "64px",
        "gap-lg": "32px",
        "table-row-height": "48px",
        "sidebar-width": "264px",
        "gap-sm": "16px",
        "gap-md": "24px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-strong": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "stat-value": ["28px", { lineHeight: "36px", letterSpacing: "-0.03em", fontWeight: "700" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
